### PR TITLE
Change python version from 2.7 to 3.6

### PR DESCRIPTION
**Pull request by marongchao**

### CODE REVIEW

**Comment by marongchao** [comment]
Merge - change python version from 2.7 to 3.6

**Comment by marongchao** [comment]
Hi Kiorky

Thanks for your quick response and comments. We need to change version to 3.6 because when i use conda with python3.6, the log shows that
"UnsatisfiableError: The following specifications were found to be in conflict:
    easydict -> python 2.7*
    python 3.6*"

Please find more details in this link 
https://github.com/makinacorpus/easydict/issues/8

Could you please elaborate a little bit more on steps I need to do for trove classifier?

It seems I need to add easydict to somehow in list for python 3.6 here https://pypi.org/search/?c=Programming+Language+%3A%3A+Python+%3A%3A+3.6?

Thanks
Rongchao

**Comment by marongchao** [comment]
Hi Kiorky

I checked a little bit more it looks like classifiers(according to link below) is the classifiers in  setup.py
 which including the python version. Please kindly correct me if I missed something.
https://packaging.python.org/tutorials/packaging-projects/#classifiers

classifiers=['Topic :: Utilities', 
                 'Natural Language :: English',
                 'Operating System :: OS Independent',
                 'Intended Audience :: Developers',
                 'Development Status :: 5 - Production/Stable',
                 'Programming Language :: Python :: 3.6'],

Thanks
Rongchao

**Comment by kiorky** [comment]
It is a python list, you need to add the trove and not replace any old other one.

**Comment by marongchao** [comment]
Hi Kiorky

Thanks for your suggestions. I've add back the old python version 2.5 in the trove classifiers. Please let me know if format is not correct because I am quite new for python package.

    classifiers=['Topic :: Utilities', 
                 'Natural Language :: English',
                 'Operating System :: OS Independent',
                 'Intended Audience :: Developers',
                 'Development Status :: 5 - Production/Stable',
                 'Programming Language :: Python :: 2.5'
                 'Programming Language :: Python :: 3.6'],

Thanks
Rongchao

**Comment by kiorky** [comment]
It's fine now, please rebase your commits before merge ! 
Thx !
@leplatrem can you add kiorky on pypi or make the release yourself after merge ?

**Comment by marongchao** [comment]
Hi Kiorky

I did rebase and there is no change in my repo. Please merge the change to main repo.

Thanks
Hongliu

**Comment by kiorky** [comment]
You need to [fixup (doc)](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history) your commits for us to merge a single and clean commit !

**Comment by marongchao** [comment]
I squash all my change in one commit. Hopefully it is good now. 

Author: rongchao <rongchao.ma@biomatrixci.com>
Date:   Wed Aug 15 00:02:47 2018 +0800

    Add python version 3.6 in classifiers

commit 2e0a7573b4057a281f08353a6cd453f4689d8f25
Author: Mathieu Leplatre <mathieu@mozilla.com>
Date:   Thu Apr 27 10:03:51 2017 +0200

    Back to development: 1.8

**Comment by SungmanHong** [comment]
CAN I install it? (I'm python 3.6)

**Pull request merged**
